config/routes.rb
RailsPrelaunchSignup::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end

  devise_scope :user do
    root :to => "devise/registrations#new"
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { :registrations => "registrations",:confirmations => "confirmations"}

  match 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite

  resources :users do
    get 'invite', :on => :member
  end

  match '/about', to: 'static#about'
  match '/how', to: 'static#how'
  match '/team', to: 'static#team'

end

app/views/layouts/_footer.html.erb
 <footer class="<%= user_signed_in? ? '' : 'anim' %>">
	<% if user_signed_in? %>
		<div class="line"> 
			<div class="text">&copy; Airfordable 2013</div>
    	</div>
	<% else %>
		<div class="line2"></div>
		<div class="container">
			<small>&copy; Airfordable 2013</small>
			<ul>
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to "Team", team_path %></li>
			</ul>
		</div>
	<% end %>
</footer>


	

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top"> 
  <% if user_signed_in? %>
    <nav class="navbar-inner">
      <div class="container">
        <%= link_to "Airfordable", root_path, :class => 'brand' %>
        <ul class="nav">
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Team", team_path %></li>
        </ul>
        <ul class="nav pull-right">
          <li><%= link_to 'Edit account', edit_user_registration_path %></li>
          <% if current_user.has_role? :admin %>
          <li><%= link_to 'Admin', users_path %></li>
          <% end %>
          <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
        </ul>
      </div>
    </nav>
  <% else %>      
    <%= render 'layouts/topnav' %>
  <% end %>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Airfordable", root_path, :class => 'brand' %>
<ul class="nav">
   <li><%= link_to "Home",    root_path %></li>
    <li><%= link_to "About",    about_path %></li>
    <li><%= link_to "Team", team_path %></li>

  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/_topnav.html.erb
     <div id="topnav"class="topnav"> 
        <%= link_to 'Already Invited?', new_user_session_path, :class => 'signin' %>
        <fieldset id="signin_menu">
          <%= simple_form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => {:class => 'form-vertical' }) do |f| %>
            <%= f.input :email, :autofocus => true %>
            <%= f.input :password %>
            <%= f.button :submit, "Sign in", :class => 'btn-primary' %>
            <%= f.input :remember_me, :as => :boolean if devise_mapping.rememberable? %>
            <%= link_to "Forgot your password?", new_password_path(resource_name) %>
          <% end %>
        </fieldset>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Airfordable Layaway for Flights" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Airfordable" %>">
    <meta name="viewport" content="width=700; initial-scale=0.9; maximum-scale=1.0;">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'> 
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <%= render 'layouts/header' %>
      <div class="container">
        <%= render 'layouts/messages' %>
        <%= yield %>
        <%= render 'layouts/footer' %>
      </div> <!--! end of .container -->
    </body>
</html>